AspNet/AuthenticationDemo/DemoApp/Models/VisitorModel.cs
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DemoApp.Models
{
    public class Visit
    {
        public int Id {get; set;}

        public string Spot {get; set;}

        public int Frequency {get; set;}

        public DateTime Recent {get; set;}

        public virtual Visitor Visitor {get; set;}

        public Visit(){}

        public Visit(string spot, Visitor visitor)
        {
            Spot = spot;
            Frequency = 1;
            Recent = DateTime.Now;
            Visitor = visitor;
        }
    }

    public class Visitor
    {
        public string Id {get; set;}

        public string Password {get; set;}

        public virtual ICollection<Visit> Visits {get; set;}

    }

    public class VisitorModel : DbContext
    {
        public DbSet<Visitor> Visitors {get; set;}

        public DbSet<Visit> Visits {get; set;}

        public VisitorModel(DbContextOptions<VisitorModel> options) : base(options) {}
    }
}

AspNet/AuthenticationDemo/DemoApp/Pages/Index.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace DemoApp.Pages
{
    using Models;

    public class IndexModel : PageModel
    {
        [BindProperty]
        public Visitor Visitor {get; set;}

        public void OnGet()
        {
            Visitor = new Visitor();
        }

        public async Task<IActionResult> OnPostAsync([FromServices] VisitorModel model)
        {
            var user = model.Visitors.Find(Visitor.Id);
            if(user == null)
            {
                model.Visitors.Add(Visitor);
                model.SaveChanges();
                user = Visitor;
            }
            else if(user.Password != Visitor.Password)
            {
                    ModelState.AddModelError("Visitor.Password", "Invalid");
                    return Page();
            }
            var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
            identity.AddClaim(new Claim(ClaimTypes.Name, Visitor.Id));
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, 
                new ClaimsPrincipal(identity),
                new AuthenticationProperties{IsPersistent = false});
            return RedirectToPage("Visitation");
        }
    }
}

AspNet/AuthenticationDemo/DemoApp/Pages/Visitation.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authentication;

namespace DemoApp.Pages
{
    using Models;

    public class VisitationModel : PageModel
    {
        private VisitorModel _model;

        public VisitationModel(VisitorModel model) => _model = model;

        public Visitor Visitor {get; set;}

        public void OnGet()
        {
            Visitor = _model.Visitors.Find(HttpContext.User.Identity.Name);
        }

        public void OnPost(string spotName)
        {
            Visitor = _model.Visitors.Find(HttpContext.User.Identity.Name);
            Visit visit = Visitor.Visits.FirstOrDefault(v => v.Spot == spotName);
            if(visit == null)
                Visitor.Visits.Add(new Visit(spotName, Visitor));
            else
            {
                visit.Frequency += 1;
                visit.Recent = System.DateTime.Now;
            }
            _model.SaveChanges();
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await HttpContext.SignOutAsync();
            return RedirectToPage("Index");
        }
    }
}

AspNet/AuthenticationDemo/DemoApp/Pages/Index.cshtml
@page
@model DemoApp.Pages.IndexModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html>
    <head>
        <title>DemoApp</title>
    </head>
    <body>
        <h1>Welcome Visitor</h1>
        <h3>Sign-In or Sign-Up</h3>
        <form method="POST">
            <table>
                <tr>
                    <td><b>Your Name:</b></td>
                    <td><input asp-for="Visitor.Id" required="required"/></td>
                </tr>
                <tr>
                    <td><b>Password:</b></td>
                    <td><input asp-for="Visitor.Password" type="password" required="required"/></td>
                    <td><span asp-validation-for="Visitor.Password"></span></td>
                </tr>
                <tr>
                    <td><input type="submit" value="Submit"/></td>
                </tr>
            </table>
        </form>
    </body>
</html>

AspNet/AuthenticationDemo/DemoApp/Pages/Visitation.cshtml
@page
@model DemoApp.Pages.VisitationModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html>
    <head>
        <title>DemoApp</title>
        <style>
            .linkButton { 
                background: none;
                border: none;
                color: #0066ff;
                text-decoration: underline;
                cursor: pointer;    
            }        
        </style>
    </head>
    <body>
        <h1>Welcome @Model.Visitor.Id</h1>
        <h3>Your Visitations</h3>
        <table border="1">
            <tr>
                <th>Spot Name</th>
                <th>Visit Count</th>
                <th>Last Visit</th>
            </tr>
            @foreach(var item in Model.Visitor.Visits)
            {
                <tr>
                    <td>@item.Spot</td>
                    <td>@item.Frequency</td>
                    <td>@item.Recent</td>
                </tr>
            }
        </table>
        <form method="POST">
            <p>
                <b>Spot Name:</b>
                <input type="text" name="spotName" required="required"/>
                <input type="submit" value="Visit"/>
            </p>
        </form>
        <form asp-page-handler="logout" method="POST">
            <input type="submit" value="Sign Out" class="linkButton"/>
        </form>
    </body>
</html>