AspNet/RazorPageDemo/DemoApp/ViewComponents/CountVisitsViewComponent.cs
using System;
using System.Collections.Concurrent;
using Microsoft.AspNetCore.Mvc;

namespace DemoApp.ViewComponents
{
    public class VisitInfo
    {
        public string Visitor {get; set;}

        public int Visits {get; set;}
    }

    public class CountVisitsViewComponent : ViewComponent
    {
        private static ConcurrentDictionary<string, int> counters = new ConcurrentDictionary<string, int>();

        public IViewComponentResult Invoke(string forName)
        {
            int count;
            counters.TryGetValue(forName, out count);
            counters[forName] = ++count;
            return View(new VisitInfo {Visitor = forName, Visits = count});
        }
    }
}

AspNet/RazorPageDemo/DemoApp/Pages/Components/CountVisits/Default.cshtml
@model DemoApp.ViewComponents.VisitInfo
<p>
    <b>Number of visits: </b>@Model.Visits
</p>

AspNet/RazorPageDemo/DemoApp/Pages/Greet.cshtml
@page "{name?}"
@{
    string visitor = (string)RouteData.Values["name"] ?? "World";    
}
@inject ISet<string> names
@functions
{
    IEnumerable<string> NamesOtherThan(string name)
    {
        lock(names)
        {
            names.Add(name);
            return from n in names where n != name select n;
        }
    }
}
@addTagHelper *, DemoApp
<!DOCTYPE html>
<html>
    <head>
        <title>DemoApp</title>
    </head>
    <body>
        <h1>Hello @visitor</h1>
        <vc:count-visits for-name="@visitor"/>
        <h2>Other Visitors</h2>
        <ol>
        @foreach(var item in NamesOtherThan(visitor))
        {
            <li><a href="/Greet/@item">@item</a></li>  
        } 
        </ol>
    </body>
</html>

AspNet/RazorPageDemo/DemoApp/Pages/Time.cshtml
@page
@DateTime.Now